name: Publish package to GitHub Packages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
